#!/bin/bash

xidfile="/run/user/"$(id -u)"/zathura-tabbed.xid"
wmclass="zathura-tabbed"

# check if a tabbed window is open
set -o pipefail
if [ -r "$xidfile" ] && xid=$(cat "$xidfile") && xprop -id "$xid" WM_CLASS 2> /dev/null | grep -q "$wmclass";
then
    wmctrl -i -R "$xid"
else
    read xid < <(tabbed -cdn "$wmclass" -p -1 2> /dev/null)
    wmctrl -i -r "$xid" -b add,maximized_vert,maximized_horz
    echo "$xid" > "$xidfile"
fi

#check if a file is already opened
d=true
for i in $(pgrep zathura); do
	if [[ $@ = $(cat /proc/$i/cmdline | awk 'BEGIN {FS="\0"} {print $4}') ]]; then
	d=false
	break
	fi
done

if [ "$d" = true ]; 
then
	zathura -e "$xid" "$@" &> /dev/null &
fi
