# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "async", "~> 2.0"

gem "async-http", "~> 0.56.5"
gem "async-process", "~> 1.3"
gem "async-websocket", "~> 0.19.0"
gem "async-rspec", "~> 1.16"
gem "async-io", "~> 1.33"
gem "async-dns", "~> 1.3"
gem "falcon", "~> 0.39.2"
gem "rubydns", "~> 2.0"

gem "rails", "~> 7.0"

gem "capybara", "~> 3.36"
