version: '3.8'

services:
  python:
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: python3 hello_world/manage.py runserver 0.0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
