# version: '3.7'
#
# services:
#     postgres:
#         image: postgres
#         restart: always
#         environment:
#             - POSTGRES_USER=postgres
#             - POSTGRES_PASSWORD=postgres
#             - POSTGRES_DATABASE=database
#             - ALLOW_EMPTY_PASSWORD=yes
#         logging:
#             options:
#                 max-size: 10m
#                 max-file: "3"
#         ports:
#             - '5438:5432'
#         volumes: 
#             - ./postgres-data:/var/lib/postgresql/data
#             # copy the sql script to create tables
#             - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
#


# app/
# database/
# docker-compose.yml

version: "3.8"
services:
    db:
        build: ./database/
        ports:
            - 5433:5432
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d
        networks:
            - app-tier
    app:
        build: ./app/
        depends_on:
            - db      
        networks:
            - app-tier      
networks:
    app-tier:
        driver: bridge
